import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const posts = api.post.all.useQuery();
  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-start justify-around p-10">
        <section className="min-h-[250px] min-w-[300px] rounded-mainRounded bg-light-blue p-5">
          <h1 className="text-4xl font-bold">BestBlog</h1>
          <button>Create Your Post</button>
        </section>
        <section className="grid h-[90vh] grid-cols-2 items-start gap-5 rounded-mainRounded bg-light-blue p-5">
          {posts.data?.map((post, idx) => (
            <article
              key={idx}
              className="h-[15vh] max-w-[25vw] rounded-subRounded bg-white p-2 hover:scale-105 hover:cursor-pointer"
            >
              <h3 className="text-lg font-bold">{post.title}</h3>
              <p>{post.createdAt.toLocaleDateString()}</p>
            </article>
          ))}
        </section>
      </main>
    </>
  );
}
